"""Add uuid to UserSettings

Revision ID: 2324ea6d53fe
Revises: 5468dbafe31d
Create Date: 2026-03-03 18:03:06.963743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2324ea6d53fe'
down_revision: Union[str, None] = '5468dbafe31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_user_settings_uuid'), 'user_settings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_uuid'), table_name='user_settings')
    op.drop_column('user_settings', 'uuid')
    # ### end Alembic commands ###
